name = "ecostride-backend"
main = "src/index.ts"
compatibility_date = "2024-09-09"

[[d1_databases]]
binding = "DB"
database_name = "ecostride-db"
database_id = "817f8335-71bd-4064-b516-664204b6ca76"

[vars]
FIREBASE_PROJECT_ID = "ecostride-0"

[triggers]
crons = ["0 * * * *"]

[[r2_buckets]]
binding = "AVATARS_BUCKET"
bucket_name = "ecostride"
preview_bucket_name = "ecostride"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "CommunityChatRoom"

[[durable_objects.bindings]]
name = "ISSUE_CHAT"
class_name = "IssueConversationDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CommunityChatRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["IssueConversationDO"]
